# import NumPy as np

In [30]:
import numpy as np

# Create an array of 10 zeros

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create an array of 10 ones

In [32]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 10 fives

In [33]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Create an array of the integers from 10 to 50

In [34]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Create an array of all the even integers from 10 to 50

In [35]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Create a 3x3 matrix with values ranging 0 to 8

In [36]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create a 3x3 identity matrix

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use numpy to generate a random number between 0 and 1

In [38]:
np.random.uniform(0,1)

0.5268082254244294

In [58]:
np.random.rand(1)

array([0.00827341])

# Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [60]:
np.random.uniform(0,1,25)

array([[0.11677367, 0.31222344, 0.05457162, 0.42455592, 0.77445889,
        0.57266016, 0.8245783 , 0.77961988, 0.44840529, 0.83078693,
        0.80364464, 0.58557065, 0.5710094 , 0.24196577, 0.07338709,
        0.67281881, 0.08573976, 0.8659847 , 0.1219927 , 0.3952605 ,
        0.02708577, 0.08144538, 0.00428098, 0.08396883, 0.3128065 ]])

In [61]:
np.random.rand(1,25)

array([[0.43234622, 0.3840341 , 0.9009542 , 0.50980423, 0.02496774,
        0.69613999, 0.00401777, 0.43640824, 0.98392804, 0.0476303 ,
        0.91026112, 0.96743247, 0.87879667, 0.06424595, 0.48792211,
        0.16069643, 0.26631459, 0.46792207, 0.11171526, 0.18644931,
        0.19573303, 0.61872622, 0.90755357, 0.95704475, 0.91299848]])

In [62]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# create an array of 20 linear spaced points between 0 and 1

In [41]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Perform on this matrice

In [42]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
np.arange(1,26).reshape(5,5)[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [48]:
np.arange(1,26).reshape(5,5)[3][-1]

20

In [52]:
np.arange(1,26).reshape(5,5)[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [53]:
np.arange(1,26).reshape(5,5)[-1]

array([21, 22, 23, 24, 25])

In [54]:
np.arange(1,26).reshape(5,5)[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
np.arange(1,26).reshape(5,5).sum()

325

In [56]:
np.arange(1,26).reshape(5,5).std()

7.211102550927978

In [57]:
np.arange(1,26).reshape(5,5).sum(axis=0)

array([55, 60, 65, 70, 75])